[config]
caching = false
expr_prefix = "{{"
expr_postfix = "}}"
block_prefix = "<*"
block_postfix = "*>"

[config.wallpaper]
set = false ## true
command = "swww img --transition-type grow {{ image }}"

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colorshypr.conf'
#post_hook = 'hyprctl reload'

[templates.alacritty]
input_path = 'templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'
# post_hook = 'hyprctl reload'

#[templates.kitty]
#input_path = 'templates/kitty-colors.conf'
#output_path = '~/.config/kitty/colors.conf'

[templates.rofi]
input_path = 'templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.Niri]
input_path = 'templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.eww]
input_path = 'templates/colors.scss'
output_path = '~/.config/eww/colors.scss'
#[templates.ewwgoth]
#input_path = 'templates/colors.scss'
#output_path = '~/.config/eww.old-goth/colors.scss'
#[templates.ewwFullbar]
#input_path = 'templates/colors.scss'
#output_path = '~/.config/eww.fullbar/colors.scss'
#post_hook = 'notify-send "updated matugen colors"'

[templates.xresources]
input_path = "templates/colors.xresources.tmpl"
output_path = "~/.config/i3/colors.Xresources"
post_hook = 'i3-msg reload'

[templates.sway]
input_path = "templates/sway.conf"
output_path = "~/.config/sway/colors.conf"

[templates.fuzzel]
input_path = 'templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

#[templates.vscode]
#input_path = '~/.config/matugen/templates/vscode.json'
#output_path = '~/.config/Code - OSS/User/settings.json'

[templates.swayncNiri]
input_path = 'templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.screenshotRofi]
input_path = 'templates/pywalfox-colors.json'
output_path = '~/HyprlandScripts/rofistyles/colors.json'

[templates.zed]
input_path = "templates/zed-colors.json"
output_path = "~/.config/zed/themes/matugen.json"

[templates.Nvim]
input_path = "templates/neovim/template.lua"
output_path = "~/.config/nvim/lua/matugen/base16.lua"

[templates.wlogout]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.mango]
input_path = './templates/mangowc.conf'
output_path = '~/.config/mango/colors.conf'
post_hook = 'mmsg -d reload_config && notify-send "mango reloaded"'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
#post_hook = 'pkill -SIGUSR2 ghostty'

#[templates.starship]
#input_path = 'templates/mystarship.toml'
#output_path = '~/.config/starship.toml'

[templates.polybar]
input_path = 'templates/mypolybar'
output_path = '~/.config/polybar/colors-polybar'
post_hook = 'polybar-msg cmd restart'
#post_hook = 'pkill -SIGUSR2 polybar || polybar &'

[templates.waybar]
input_path = 'templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.swayosd]
input_path = 'templates/colors.css'
output_path = '~/.config/swayosd/colors.css'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.quickshell]
input_path = './templates/quickshell.qml'
output_path = '~/.config/quickshell/Colors.qml'
#post_hook = 'pkill -USR1 quickshell; quickshell &'
post_hook = 'notify-send "updated matugen colors"'

