[config]
caching = false
expr_prefix = "{{"
expr_postfix = "}}"
block_prefix = "<*"
block_postfix = "*>"

[config.wallpaper]
set = false ## true
command = "swww img --transition-type grow {{ image }}"

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colorshypr.conf'
#post_hook = 'hyprctl reload'

[templates.alacritty]
input_path = 'templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'
# post_hook = 'hyprctl reload'

[templates.kitty]
input_path = 'templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.rofi]
input_path = 'templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.Niri]
input_path = 'templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.eww]
input_path = 'templates/colors.scss'
output_path = '~/.config/eww/colors.scss'
#post_hook = 'notify-send "updated matugen colors"'

[templates.xresources]
input_path = "templates/colors.xresources.tmpl"
output_path = "~/.config/i3/colors.Xresources"

[templates.fuzzel]
input_path = 'templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

#[templates.vscode]
#input_path = '~/.config/matugen/templates/vscode.json'
#output_path = '~/.config/Code - OSS/User/settings.json'

[templates.swayncNiri]
input_path = 'templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.screenshotRofi]
input_path = 'templates/pywalfox-colors.json'
output_path = '~/HyprlandScripts/rofistyles/colors.json'

[templates.zed]
input_path = "templates/zed-colors.json"
output_path = "~/.config/zed/themes/matugen.json"

[templates.Nvim]
input_path = "templates/neovim/template.lua"
output_path = "~/.config/nvim/lua/matugen/base16.lua"

[templates.wlogout]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.waybar]
input_path = 'templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'notify-send "updated matugen colors"'

