[colors.primary]
background = '#1a110e'
#background = '#71361a'
foreground = '#ffdbcd'
 
[colors.cursor]
text = '#f1dfd9'
cursor = '#d8c2ba' 
 
[colors.vi_mode_cursor]
text = '#1a110e'
cursor = '#ffb596' 
 
[colors.search.matches]
foreground = '#53443e' 
background = '#d2c78f' 
 
[colors.search.focused_match]
foreground = '#53443e' 
background = '#ffb596' 
 
[colors.footer_bar]
foreground = '#53443e' 
background = '#f1dfd9' 
 
[colors.hints.start]
foreground = '#53443e' 
background = '#e6beae' 
 
[colors.hints.end]
foreground = '#53443e' 
background = '#e6beae' 
 
[colors.selection]
text = '#1a110e'
background = '#ffb596'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb596' 
yellow = '#8e4d2f' 
blue = '#ffb596' 
magenta = '#d2c78f' 
cyan = '#e6beae' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
