[colors.primary]
background = '#19120d'
foreground = '#ffdbc7'
 
[colors.cursor]
text = '#f0dfd7'
cursor = '#d7c3b8' 
 
[colors.vi_mode_cursor]
text = '#19120d'
cursor = '#ffb688' 
 
[colors.search.matches]
foreground = '#52443c' 
background = '#caca93' 
 
[colors.search.focused_match]
foreground = '#52443c' 
background = '#ffb688' 
 
[colors.footer_bar]
foreground = '#52443c' 
background = '#f0dfd7' 
 
[colors.hints.start]
foreground = '#52443c' 
background = '#e5bfa9' 
 
[colors.hints.end]
foreground = '#52443c' 
background = '#e5bfa9' 
 
[colors.selection]
text = '#19120d'
background = '#ffb688'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb688' 
yellow = '#8b4f24' 
blue = '#ffb688' 
magenta = '#caca93' 
cyan = '#e5bfa9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
